name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv venv
          uv pip install .[dev]
      - name: Lint (ruff)
        run: ruff check src tests
      - name: Format check (black)
        run: black --check src tests
      - name: Type check (mypy)
        run: mypy src
      - name: Run tests
        run: pytest -m "not integration" -q
