name: CI

on:
  pull_request:
    branches: [ "**" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Setup uv
        uses: astral-sh/setup-uv@v3
      - name: Install dependencies
        run: uv sync --dev
      - name: Lint (ruff)
        run: uv run ruff check src tests
      - name: Format check (black)
        run: uv run black --check src tests
      - name: Type check (mypy)
        run: uv run mypy src
      - name: Run tests
        run: uv run pytest -m "not integration" -q
